#pragma once
#include "AbstractQuery/AbstractQuery.hpp"
#include "CreateTableQuery/CreateTableQuery.hpp"
#include "DropTableQuery/DropTableQuery.hpp"
#include "TruncateTableQuery/TruncateTableQuery.hpp"
#include "DisplayQuery/DisplayQuery.hpp"
#include "InsertIntoQuery/InsertIntoQuery.hpp"
#include "SelectQuery/SelectQuery.hpp"
#include "DeleteQuery/DeleteQuery.hpp"